### PR TITLE
Fix/preview wrong loaded state

### LINKED ISSUE #71: Accept changes enhancement
After a chat response has been generated and user leaves the chat, and back, the accept changes button dissaperas and then appears in a few seconds. That wait time is confusing.

Add a processing UI in between the wait time

### LINKED ISSUE #81: Clickable features in preview bug
The navbar on the bottom shouldn't be clickable during preview 

Image

### PR DESCRIPTION
**Pull request by eyadfhafi**

### CODE REVIEW

File: lib/routes/authentication/AuthorizedRoute.dart [hunk 1]
```diff
@@ -629,8 +629,10 @@ class AuthorizedRouteState extends State<AuthorizedRoute>
       var eventNameSearch = this.generateSearchWidget();
       widgetChildren.add(eventNameSearch);
     } else {
-      bottomNavigator = _buildBottomNavBar(
-          BlocProvider.of<VibeChatBloc>(context).state.step);
+      bottomNavigator = BlocBuilder<VibeChatBloc, VibeChatState>(
```
Comment (jerbio) [inline lib/routes/authentication/AuthorizedRoute.dart]: You cannot use a new context here because this new Blocs do not have the device Location bloc in them so they fail to trigger the device locaiton picker

File: lib/routes/authentication/AuthorizedRoute.dart [hunk 2]
```diff
@@ -644,8 +646,10 @@ class AuthorizedRouteState extends State<AuthorizedRoute>
         ),
       ),
       bottomNavigationBar: bottomNavigator,
-      floatingActionButton: _buildPreviewFloatingActionButton(
-          BlocProvider.of<VibeChatBloc>(context).state.step),
+      floatingActionButton: BlocBuilder<VibeChatBloc, VibeChatState>(
```
Comment (jerbio) [inline lib/routes/authentication/AuthorizedRoute.dart]: SAA

**Review by jerbio — CHANGES_REQUESTED** [review]
